---
# Список кастомных групп
custom_groups:
  - admins
  - deploy

# Определение пользователей
users:
  - name: deployer
    shell: /bin/bash
    state: present
    public_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADA...FxJScQjJfyQ== deployer"
    password: "{{ 'deployer' | password_hash('sha512') }}"
    groups:
      - sudo
      - deploy

  - name: admin
    shell: /bin/zsh
    state: present
    public_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADA...hgtp/m+kdLw== admin"
    password: "{{ 'admin' | password_hash('sha512') }}"
    groups:
      - admins
