---
- name: Устанавливаем nginx
  apt:
    name: nginx
    state: present

- name: Удаляем дефолтный сайт nginx
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: reload-services-1

- name: Разворачиваем конфигурацию nginx для статики
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/static_server.conf
    mode: 0644
  notify: reload-services-1

- name: Включаем сайт (создаем символьную ссылку)
  file:
    src: /etc/nginx/sites-available/static_server.conf
    dest: /etc/nginx/sites-enabled/static_server.conf
    state: link
  notify: reload-services-1
