---
- name: Playbook для настройки сервера
  hosts: static_server
  become: yes
  vars_files:
    - vars/main.yml
  roles:
    - users
    - ssh
    - utils
    - ohmyzsh
    - nginx
    - static

  tasks:
  - name: Запустить все обработчики
    meta: flush_handlers
